/* Generated by `dev/translate-clap-structs.js` - do not edit by hand */

//---------- version.h
export const VERSION_MAJOR = 1;
export const VERSION_MINOR = 2;
export const VERSION_REVISION = 7;
@unmanaged
export class clap_version {
	_major : u32;
	_minor : u32;
	_revision : u32;
}

//---------- entry.h
@unmanaged
export class clap_plugin_entry {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_plugin_entry>("_clap_version_major"))
	}
	_init : usize; // (const char *plugin_path) -> bool
	_deinit : usize; // () -> void
	_get_factory : usize; // (const char *factory_id) -> const void *
}

//---------- host.h
@unmanaged
export class clap_host {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_host>("_clap_version_major"))
	}
	_host_data : usize; // void *
	_name : usize; // const char *
	_vendor : usize; // const char *
	_url : usize; // const char *
	_version : usize; // const char *
	_get_extension : usize; // (const struct clap_host *host,const char *extension_id) -> const void *
	_request_restart : usize; // (const struct clap_host *host) -> void
	_request_process : usize; // (const struct clap_host *host) -> void
	_request_callback : usize; // (const struct clap_host *host) -> void
}

//---------- fixedpoint.h
export type clap_beattime = i64;
export type clap_sectime = i64;
export const BEATTIME_FACTOR = 0x80000000;
export const SECTIME_FACTOR = 0x80000000;

//---------- id.h
export type clap_id = u32;

//---------- events.h
export type clap_note_expression = i32;
export const CORE_EVENT_SPACE_ID = 0;
export const EVENT_IS_LIVE = 1 << 0;
export const EVENT_DONT_RECORD = 1 << 1;
export const EVENT_NOTE_ON = 0;
export const EVENT_NOTE_OFF = 1;
export const EVENT_NOTE_CHOKE = 2;
export const EVENT_NOTE_END = 3;
export const EVENT_NOTE_EXPRESSION = 4;
export const EVENT_PARAM_VALUE = 5;
export const EVENT_PARAM_MOD = 6;
export const EVENT_PARAM_GESTURE_BEGIN = 7;
export const EVENT_PARAM_GESTURE_END = 8;
export const EVENT_TRANSPORT = 9;
export const EVENT_MIDI = 10;
export const EVENT_MIDI_SYSEX = 11;
export const NOTE_EXPRESSION_VOLUME = 0;
export const NOTE_EXPRESSION_PAN = 1;
export const NOTE_EXPRESSION_TUNING = 2;
export const NOTE_EXPRESSION_VIBRATO = 3;
export const NOTE_EXPRESSION_EXPRESSION = 4;
export const NOTE_EXPRESSION_BRIGHTNESS = 5;
export const NOTE_EXPRESSION_PRESSURE = 6;
export const TRANSPORT_HAS_TEMPO = 1 << 0;
export const TRANSPORT_HAS_BEATS_TIMELINE = 1 << 1;
export const TRANSPORT_HAS_SECONDS_TIMELINE = 1 << 2;
export const TRANSPORT_HAS_TIME_SIGNATURE = 1 << 3;
export const TRANSPORT_IS_PLAYING = 1 << 4;
export const TRANSPORT_IS_RECORDING = 1 << 5;
export const TRANSPORT_IS_LOOP_ACTIVE = 1 << 6;
export const TRANSPORT_IS_WITHIN_PRE_ROLL = 1 << 7;
@unmanaged
export class clap_event_header {
	_size : u32;
	_time : u32;
	_space_id : u16;
	_type : u16;
	_flags : u32;
}
@unmanaged
export class clap_event_note {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_note>("_header_size"))
	}
	_note_id : i32;
	_port_index : i16;
	_channel : i16;
	_key : i16;
	_velocity : f64;
}
@unmanaged
export class clap_event_note_expression {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_note_expression>("_header_size"))
	}
	_expression_id : clap_note_expression;
	_note_id : i32;
	_port_index : i16;
	_channel : i16;
	_key : i16;
	_value : f64;
}
@unmanaged
export class clap_event_param_value {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_param_value>("_header_size"))
	}
	_param_id : clap_id;
	_cookie : usize; // void *
	_note_id : i32;
	_port_index : i16;
	_channel : i16;
	_key : i16;
	_value : f64;
}
@unmanaged
export class clap_event_param_mod {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_param_mod>("_header_size"))
	}
	_param_id : clap_id;
	_cookie : usize; // void *
	_note_id : i32;
	_port_index : i16;
	_channel : i16;
	_key : i16;
	_amount : f64;
}
@unmanaged
export class clap_event_param_gesture {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_param_gesture>("_header_size"))
	}
	_param_id : clap_id;
}
@unmanaged
export class clap_event_transport {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_transport>("_header_size"))
	}
	_flags : u32;
	_song_pos_beats : clap_beattime;
	_song_pos_seconds : clap_sectime;
	_tempo : f64;
	_tempo_inc : f64;
	_loop_start_beats : clap_beattime;
	_loop_end_beats : clap_beattime;
	_loop_start_seconds : clap_sectime;
	_loop_end_seconds : clap_sectime;
	_bar_start : clap_beattime;
	_bar_number : i32;
	_tsig_num : u16;
	_tsig_denom : u16;
}
@unmanaged
export class clap_event_midi {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_midi>("_header_size"))
	}
	_port_index : u16;
	@array(3) _data : u8;
}
@unmanaged
export class clap_event_midi_sysex {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_midi_sysex>("_header_size"))
	}
	_port_index : u16;
	_buffer : usize; // const uint8_t *
	_size : u32;
}
@unmanaged
export class clap_event_midi2 {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_midi2>("_header_size"))
	}
	_port_index : u16;
	@array(4) _data : u32;
}
@unmanaged
export class clap_input_events {
	_ctx : usize; // void *
	_size : usize; // (const struct clap_input_events *list) -> uint32_t
	_get : usize; // (const struct clap_input_events *list,uint32_t index) -> const clap_event_header_t *
}
@unmanaged
export class clap_output_events {
	_ctx : usize; // void *
	_try_push : usize; // (const struct clap_output_events *list,const clap_event_header_t *event) -> bool
}

//---------- audio-buffer.h
@unmanaged
export class clap_audio_buffer {
	_data32 : usize; // float **
	_data64 : usize; // double **
	_channel_count : u32;
	_latency : u32;
	_constant_mask : u64;
}

//---------- process.h
export type clap_process_status = i32;
export const PROCESS_ERROR = 0;
export const PROCESS_CONTINUE = 1;
export const PROCESS_CONTINUE_IF_NOT_QUIET = 2;
export const PROCESS_TAIL = 3;
export const PROCESS_SLEEP = 4;
@unmanaged
export class clap_process {
	_steady_time : i64;
	_frames_count : u32;
	_transport : usize; // const clap_event_transport_t *
	_audio_inputs : usize; // const clap_audio_buffer_t *
	_audio_outputs : usize; // clap_audio_buffer_t *
	_audio_inputs_count : u32;
	_audio_outputs_count : u32;
	_in_events : usize; // const clap_input_events_t *
	_out_events : usize; // const clap_output_events_t *
}

//---------- plugin-features.h
export const PLUGIN_FEATURE_INSTRUMENT = "instrument";
export const PLUGIN_FEATURE_AUDIO_EFFECT = "audio-effect";
export const PLUGIN_FEATURE_NOTE_EFFECT = "note-effect";
export const PLUGIN_FEATURE_NOTE_DETECTOR = "note-detector";
export const PLUGIN_FEATURE_ANALYZER = "analyzer";
export const PLUGIN_FEATURE_SYNTHESIZER = "synthesizer";
export const PLUGIN_FEATURE_SAMPLER = "sampler";
export const PLUGIN_FEATURE_DRUM = "drum";
export const PLUGIN_FEATURE_DRUM_MACHINE = "drum-machine";
export const PLUGIN_FEATURE_FILTER = "filter";
export const PLUGIN_FEATURE_PHASER = "phaser";
export const PLUGIN_FEATURE_EQUALIZER = "equalizer";
export const PLUGIN_FEATURE_DEESSER = "de-esser";
export const PLUGIN_FEATURE_PHASE_VOCODER = "phase-vocoder";
export const PLUGIN_FEATURE_GRANULAR = "granular";
export const PLUGIN_FEATURE_FREQUENCY_SHIFTER = "frequency-shifter";
export const PLUGIN_FEATURE_PITCH_SHIFTER = "pitch-shifter";
export const PLUGIN_FEATURE_DISTORTION = "distortion";
export const PLUGIN_FEATURE_TRANSIENT_SHAPER = "transient-shaper";
export const PLUGIN_FEATURE_COMPRESSOR = "compressor";
export const PLUGIN_FEATURE_EXPANDER = "expander";
export const PLUGIN_FEATURE_GATE = "gate";
export const PLUGIN_FEATURE_LIMITER = "limiter";
export const PLUGIN_FEATURE_FLANGER = "flanger";
export const PLUGIN_FEATURE_CHORUS = "chorus";
export const PLUGIN_FEATURE_DELAY = "delay";
export const PLUGIN_FEATURE_REVERB = "reverb";
export const PLUGIN_FEATURE_TREMOLO = "tremolo";
export const PLUGIN_FEATURE_GLITCH = "glitch";
export const PLUGIN_FEATURE_UTILITY = "utility";
export const PLUGIN_FEATURE_PITCH_CORRECTION = "pitch-correction";
export const PLUGIN_FEATURE_RESTORATION = "restoration";
export const PLUGIN_FEATURE_MULTI_EFFECTS = "multi-effects";
export const PLUGIN_FEATURE_MIXING = "mixing";
export const PLUGIN_FEATURE_MASTERING = "mastering";
export const PLUGIN_FEATURE_MONO = "mono";
export const PLUGIN_FEATURE_STEREO = "stereo";
export const PLUGIN_FEATURE_SURROUND = "surround";
export const PLUGIN_FEATURE_AMBISONIC = "ambisonic";

//---------- plugin.h
@unmanaged
export class clap_plugin_descriptor {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_plugin_descriptor>("_clap_version_major"))
	}
	_id : usize; // const char *
	_name : usize; // const char *
	_vendor : usize; // const char *
	_url : usize; // const char *
	_manual_url : usize; // const char *
	_support_url : usize; // const char *
	_version : usize; // const char *
	_description : usize; // const char *
	_features : usize; // const char *const *
}
@unmanaged
export class clap_plugin {
	_desc : usize; // const clap_plugin_descriptor_t *
	_plugin_data : usize; // void *
	_init : usize; // (const struct clap_plugin *plugin) -> bool
	_destroy : usize; // (const struct clap_plugin *plugin) -> void
	_activate : usize; // (const struct clap_plugin *plugin,double sample_rate,uint32_t min_frames_count,uint32_t max_frames_count) -> bool
	_deactivate : usize; // (const struct clap_plugin *plugin) -> void
	_start_processing : usize; // (const struct clap_plugin *plugin) -> bool
	_stop_processing : usize; // (const struct clap_plugin *plugin) -> void
	_reset : usize; // (const struct clap_plugin *plugin) -> void
	_process : usize; // (const struct clap_plugin *plugin,const clap_process_t *process) -> clap_process_status
	_get_extension : usize; // (const struct clap_plugin *plugin,const char *id) -> const void *
	_on_main_thread : usize; // (const struct clap_plugin *plugin) -> void
}

//---------- factory/plugin-factory.h
@unmanaged
export class clap_plugin_factory {
	_get_plugin_count : usize; // (const struct clap_plugin_factory *factory) -> uint32_t
	_get_plugin_descriptor : usize; // (const struct clap_plugin_factory *factory,uint32_t index) -> const clap_plugin_descriptor_t *
	_create_plugin : usize; // (const struct clap_plugin_factory *factory,const clap_host_t *host,const char *plugin_id) -> const clap_plugin_t *
}

//---------- private/macros.h

//---------- private/std.h

//---------- timestamp.h
export type clap_timestamp = u64;
export const TIMESTAMP_UNKNOWN = 0;

//---------- universal-plugin-id.h
@unmanaged
export class clap_universal_plugin_id {
	_abi : usize; // const char *
	_id : usize; // const char *
}

//---------- factory/preset-discovery.h
export const PRESET_DISCOVERY_LOCATION_FILE = 0;
export const PRESET_DISCOVERY_LOCATION_PLUGIN = 1;
export const PRESET_DISCOVERY_IS_FACTORY_CONTENT = 1 << 0;
export const PRESET_DISCOVERY_IS_USER_CONTENT = 1 << 1;
export const PRESET_DISCOVERY_IS_DEMO_CONTENT = 1 << 2;
export const PRESET_DISCOVERY_IS_FAVORITE = 1 << 3;
@unmanaged
export class clap_preset_discovery_metadata_receiver {
	_receiver_data : usize; // void *
	_on_error : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,int32_t os_error,const char *error_message) -> void
	_begin_preset : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *name,const char *load_key) -> bool
	_add_plugin_id : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const clap_universal_plugin_id_t *plugin_id) -> void
	_set_soundpack_id : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *soundpack_id) -> void
	_set_flags : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,uint32_t flags) -> void
	_add_creator : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *creator) -> void
	_set_description : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *description) -> void
	_set_timestamps : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,clap_timestamp creation_time,clap_timestamp modification_time) -> void
	_add_feature : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *feature) -> void
	_add_extra_info : usize; // (const struct clap_preset_discovery_metadata_receiver *receiver,const char *key,const char *value) -> void
}
@unmanaged
export class clap_preset_discovery_filetype {
	_name : usize; // const char *
	_description : usize; // const char *
	_file_extension : usize; // const char *
}
@unmanaged
export class clap_preset_discovery_location {
	_flags : u32;
	_name : usize; // const char *
	_kind : u32;
	_location : usize; // const char *
}
@unmanaged
export class clap_preset_discovery_soundpack {
	_flags : u32;
	_id : usize; // const char *
	_name : usize; // const char *
	_description : usize; // const char *
	_homepage_url : usize; // const char *
	_vendor : usize; // const char *
	_image_path : usize; // const char *
	_release_timestamp : clap_timestamp;
}
@unmanaged
export class clap_preset_discovery_provider_descriptor {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_preset_discovery_provider_descriptor>("_clap_version_major"))
	}
	_id : usize; // const char *
	_name : usize; // const char *
	_vendor : usize; // const char *
}
@unmanaged
export class clap_preset_discovery_provider {
	_desc : usize; // const clap_preset_discovery_provider_descriptor_t *
	_provider_data : usize; // void *
	_init : usize; // (const struct clap_preset_discovery_provider *provider) -> bool
	_destroy : usize; // (const struct clap_preset_discovery_provider *provider) -> void
	_get_metadata : usize; // (const struct clap_preset_discovery_provider *provider,uint32_t location_kind,const char *location,const clap_preset_discovery_metadata_receiver_t *metadata_receiver) -> bool
	_get_extension : usize; // (const struct clap_preset_discovery_provider *provider,const char *extension_id) -> const void *
}
@unmanaged
export class clap_preset_discovery_indexer {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_preset_discovery_indexer>("_clap_version_major"))
	}
	_name : usize; // const char *
	_vendor : usize; // const char *
	_url : usize; // const char *
	_version : usize; // const char *
	_indexer_data : usize; // void *
	_declare_filetype : usize; // (const struct clap_preset_discovery_indexer *indexer,const clap_preset_discovery_filetype_t *filetype) -> bool
	_declare_location : usize; // (const struct clap_preset_discovery_indexer *indexer,const clap_preset_discovery_location_t *location) -> bool
	_declare_soundpack : usize; // (const struct clap_preset_discovery_indexer *indexer,const clap_preset_discovery_soundpack_t *soundpack) -> bool
	_get_extension : usize; // (const struct clap_preset_discovery_indexer *indexer,const char *extension_id) -> const void *
}
@unmanaged
export class clap_preset_discovery_factory {
	_count : usize; // (const struct clap_preset_discovery_factory *factory) -> uint32_t
	_get_descriptor : usize; // (const struct clap_preset_discovery_factory *factory,uint32_t index) -> const clap_preset_discovery_provider_descriptor_t *
	_create : usize; // (const struct clap_preset_discovery_factory *factory,const clap_preset_discovery_indexer_t *indexer,const char *provider_id) -> const clap_preset_discovery_provider_t *
}

//---------- ext/ambisonic.h
export const AMBISONIC_ORDERING_FUMA = 0;
export const AMBISONIC_ORDERING_ACN = 1;
export const AMBISONIC_NORMALIZATION_MAXN = 0;
export const EXT_AMBISONIC = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x6d,0x62,0x69,0x73,0x6f,0x6e,0x69,0x63,0x2f,0x33,0x0]); // clap.ambisonic/3
export const EXT_AMBISONIC_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x6d,0x62,0x69,0x73,0x6f,0x6e,0x69,0x63,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x33,0x0]); // clap.ambisonic.draft/3
export const PORT_AMBISONIC = memory.data<u8>([0x61,0x6d,0x62,0x69,0x73,0x6f,0x6e,0x69,0x63,0x0]); // ambisonic
@unmanaged
export class clap_ambisonic_config {
	_ordering : u32;
	_normalization : u32;
}
@unmanaged
export class clap_plugin_ambisonic {
	_is_config_supported : usize; // (const clap_plugin_t *plugin,const clap_ambisonic_config_t *config) -> bool
	_get_config : usize; // (const clap_plugin_t *plugin,bool is_input,uint32_t port_index,clap_ambisonic_config_t *config) -> bool
}
@unmanaged
export class clap_host_ambisonic {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- ext/audio-ports-activation.h
export const EXT_AUDIO_PORTS_ACTIVATION = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2d,0x61,0x63,0x74,0x69,0x76,0x61,0x74,0x69,0x6f,0x6e,0x2f,0x32,0x0]); // clap.audio-ports-activation/2
export const EXT_AUDIO_PORTS_ACTIVATION_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2d,0x61,0x63,0x74,0x69,0x76,0x61,0x74,0x69,0x6f,0x6e,0x2f,0x64,0x72,0x61,0x66,0x74,0x2d,0x32,0x0]); // clap.audio-ports-activation/draft-2
@unmanaged
export class clap_plugin_audio_ports_activation {
	_can_activate_while_processing : usize; // (const clap_plugin_t *plugin) -> bool
	_set_active : usize; // (const clap_plugin_t *plugin,bool is_input,uint32_t port_index,bool is_active,uint32_t sample_size) -> bool
}

//---------- string-sizes.h

//---------- ext/audio-ports.h
export const AUDIO_PORT_IS_MAIN = 1 << 0;
export const AUDIO_PORT_REQUIRES_COMMON_SAMPLE_SIZE = 1 << 3;
export const AUDIO_PORTS_RESCAN_NAMES = 1 << 0;
export const AUDIO_PORTS_RESCAN_FLAGS = 1 << 1;
export const AUDIO_PORTS_RESCAN_CHANNEL_COUNT = 1 << 2;
export const AUDIO_PORTS_RESCAN_PORT_TYPE = 1 << 3;
export const AUDIO_PORTS_RESCAN_IN_PLACE_PAIR = 1 << 4;
export const AUDIO_PORTS_RESCAN_LIST = 1 << 5;
export const EXT_AUDIO_PORTS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x0]); // clap.audio-ports
export const PORT_MONO = memory.data<u8>([0x6d,0x6f,0x6e,0x6f,0x0]); // mono
export const PORT_STEREO = memory.data<u8>([0x73,0x74,0x65,0x72,0x65,0x6f,0x0]); // stereo
@unmanaged
export class clap_audio_port_info {
	_id : clap_id;
	@array(256) _name : i8;
	_flags : u32;
	_channel_count : u32;
	_port_type : usize; // const char *
	_in_place_pair : clap_id;
}
@unmanaged
export class clap_plugin_audio_ports {
	_count : usize; // (const clap_plugin_t *plugin,bool is_input) -> uint32_t
	_get : usize; // (const clap_plugin_t *plugin,uint32_t index,bool is_input,clap_audio_port_info_t *info) -> bool
}
@unmanaged
export class clap_host_audio_ports {
	_is_rescan_flag_supported : usize; // (const clap_host_t *host,uint32_t flag) -> bool
	_rescan : usize; // (const clap_host_t *host,uint32_t flags) -> void
}

//---------- ext/audio-ports-config.h
export const EXT_AUDIO_PORTS_CONFIG = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2d,0x63,0x6f,0x6e,0x66,0x69,0x67,0x0]); // clap.audio-ports-config
export const EXT_AUDIO_PORTS_CONFIG_INFO = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2d,0x63,0x6f,0x6e,0x66,0x69,0x67,0x2d,0x69,0x6e,0x66,0x6f,0x2f,0x31,0x0]); // clap.audio-ports-config-info/1
export const EXT_AUDIO_PORTS_CONFIG_INFO_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2d,0x63,0x6f,0x6e,0x66,0x69,0x67,0x2d,0x69,0x6e,0x66,0x6f,0x2f,0x64,0x72,0x61,0x66,0x74,0x2d,0x30,0x0]); // clap.audio-ports-config-info/draft-0
@unmanaged
export class clap_audio_ports_config {
	_id : clap_id;
	@array(256) _name : i8;
	_input_port_count : u32;
	_output_port_count : u32;
	_has_main_input : bool;
	_main_input_channel_count : u32;
	_main_input_port_type : usize; // const char *
	_has_main_output : bool;
	_main_output_channel_count : u32;
	_main_output_port_type : usize; // const char *
}
@unmanaged
export class clap_plugin_audio_ports_config {
	_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get : usize; // (const clap_plugin_t *plugin,uint32_t index,clap_audio_ports_config_t *config) -> bool
	_select : usize; // (const clap_plugin_t *plugin,clap_id config_id) -> bool
}
@unmanaged
export class clap_plugin_audio_ports_config_info {
	_current_config : usize; // (const clap_plugin_t *plugin) -> clap_id
	_get : usize; // (const clap_plugin_t *plugin,clap_id config_id,uint32_t port_index,bool is_input,clap_audio_port_info_t *info) -> bool
}
@unmanaged
export class clap_host_audio_ports_config {
	_rescan : usize; // (const clap_host_t *host) -> void
}

//---------- ext/configurable-audio-ports.h
export const EXT_CONFIGURABLE_AUDIO_PORTS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x63,0x6f,0x6e,0x66,0x69,0x67,0x75,0x72,0x61,0x62,0x6c,0x65,0x2d,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2f,0x31,0x0]); // clap.configurable-audio-ports/1
export const EXT_CONFIGURABLE_AUDIO_PORTS_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x63,0x6f,0x6e,0x66,0x69,0x67,0x75,0x72,0x61,0x62,0x6c,0x65,0x2d,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2e,0x64,0x72,0x61,0x66,0x74,0x31,0x0]); // clap.configurable-audio-ports.draft1
@unmanaged
export class clap_audio_port_configuration_request {
	_is_input : bool;
	_port_index : u32;
	_channel_count : u32;
	_port_type : usize; // const char *
	_port_details : usize; // const void *
}
@unmanaged
export class clap_plugin_configurable_audio_ports {
	_can_apply_configuration : usize; // (const clap_plugin_t *plugin,const struct clap_audio_port_configuration_request *requests,uint32_t request_count) -> bool
	_apply_configuration : usize; // (const clap_plugin_t *plugin,const struct clap_audio_port_configuration_request *requests,uint32_t request_count) -> bool
}

//---------- ext/context-menu.h
export type clap_context_menu_item_kind_t = u32;
export const CONTEXT_MENU_TARGET_KIND_GLOBAL = 0;
export const CONTEXT_MENU_TARGET_KIND_PARAM = 1;
export const EXT_CONTEXT_MENU = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x63,0x6f,0x6e,0x74,0x65,0x78,0x74,0x2d,0x6d,0x65,0x6e,0x75,0x2f,0x31,0x0]); // clap.context-menu/1
export const EXT_CONTEXT_MENU_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x63,0x6f,0x6e,0x74,0x65,0x78,0x74,0x2d,0x6d,0x65,0x6e,0x75,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x30,0x0]); // clap.context-menu.draft/0
@unmanaged
export class clap_context_menu_target {
	_kind : u32;
	_id : clap_id;
}
@unmanaged
export class clap_context_menu_entry {
	_label : usize; // const char *
	_is_enabled : bool;
	_action_id : clap_id;
}
@unmanaged
export class clap_context_menu_check_entry {
	_label : usize; // const char *
	_is_enabled : bool;
	_is_checked : bool;
	_action_id : clap_id;
}
@unmanaged
export class clap_context_menu_item_title {
	_title : usize; // const char *
	_is_enabled : bool;
}
@unmanaged
export class clap_context_menu_submenu {
	_label : usize; // const char *
	_is_enabled : bool;
}
@unmanaged
export class clap_context_menu_builder {
	_ctx : usize; // void *
	_add_item : usize; // (const struct clap_context_menu_builder *builder,clap_context_menu_item_kind_t item_kind,const void *item_data) -> bool
	_supports : usize; // (const struct clap_context_menu_builder *builder,clap_context_menu_item_kind_t item_kind) -> bool
}
@unmanaged
export class clap_plugin_context_menu {
	_populate : usize; // (const clap_plugin_t *plugin,const clap_context_menu_target_t *target,const clap_context_menu_builder_t *builder) -> bool
	_perform : usize; // (const clap_plugin_t *plugin,const clap_context_menu_target_t *target,clap_id action_id) -> bool
}
@unmanaged
export class clap_host_context_menu {
	_populate : usize; // (const clap_host_t *host,const clap_context_menu_target_t *target,const clap_context_menu_builder_t *builder) -> bool
	_perform : usize; // (const clap_host_t *host,const clap_context_menu_target_t *target,clap_id action_id) -> bool
	_can_popup : usize; // (const clap_host_t *host) -> bool
	_popup : usize; // (const clap_host_t *host,const clap_context_menu_target_t *target,int32_t screen_index,int32_t x,int32_t y) -> bool
}

//---------- ext/event-registry.h
export const EXT_EVENT_REGISTRY = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x65,0x76,0x65,0x6e,0x74,0x2d,0x72,0x65,0x67,0x69,0x73,0x74,0x72,0x79,0x0]); // clap.event-registry
@unmanaged
export class clap_host_event_registry {
	_query : usize; // (const clap_host_t *host,const char *space_name,uint16_t *space_id) -> bool
}

//---------- ext/gui.h
// skipped clap_xwnd
export const EXT_GUI = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x67,0x75,0x69,0x0]); // clap.gui
// skipped clap_window
@unmanaged
export class clap_gui_resize_hints {
	_can_resize_horizontally : bool;
	_can_resize_vertically : bool;
	_preserve_aspect_ratio : bool;
	_aspect_ratio_width : u32;
	_aspect_ratio_height : u32;
}
@unmanaged
export class clap_plugin_gui {
	_is_api_supported : usize; // (const clap_plugin_t *plugin,const char *api,bool is_floating) -> bool
	_get_preferred_api : usize; // (const clap_plugin_t *plugin,const char **api,bool *is_floating) -> bool
	_create : usize; // (const clap_plugin_t *plugin,const char *api,bool is_floating) -> bool
	_destroy : usize; // (const clap_plugin_t *plugin) -> void
	_set_scale : usize; // (const clap_plugin_t *plugin,double scale) -> bool
	_get_size : usize; // (const clap_plugin_t *plugin,uint32_t *width,uint32_t *height) -> bool
	_can_resize : usize; // (const clap_plugin_t *plugin) -> bool
	_get_resize_hints : usize; // (const clap_plugin_t *plugin,clap_gui_resize_hints_t *hints) -> bool
	_adjust_size : usize; // (const clap_plugin_t *plugin,uint32_t *width,uint32_t *height) -> bool
	_set_size : usize; // (const clap_plugin_t *plugin,uint32_t width,uint32_t height) -> bool
	_set_parent : usize; // (const clap_plugin_t *plugin,const clap_window_t *window) -> bool
	_set_transient : usize; // (const clap_plugin_t *plugin,const clap_window_t *window) -> bool
	_suggest_title : usize; // (const clap_plugin_t *plugin,const char *title) -> void
	_show : usize; // (const clap_plugin_t *plugin) -> bool
	_hide : usize; // (const clap_plugin_t *plugin) -> bool
}
@unmanaged
export class clap_host_gui {
	_resize_hints_changed : usize; // (const clap_host_t *host) -> void
	_request_resize : usize; // (const clap_host_t *host,uint32_t width,uint32_t height) -> bool
	_request_show : usize; // (const clap_host_t *host) -> bool
	_request_hide : usize; // (const clap_host_t *host) -> bool
	_closed : usize; // (const clap_host_t *host,bool was_destroyed) -> void
}

//---------- ext/latency.h
export const EXT_LATENCY = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x6c,0x61,0x74,0x65,0x6e,0x63,0x79,0x0]); // clap.latency
@unmanaged
export class clap_plugin_latency {
	_get : usize; // (const clap_plugin_t *plugin) -> uint32_t
}
@unmanaged
export class clap_host_latency {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- ext/log.h
export type clap_log_severity = i32;
export const LOG_DEBUG = 0;
export const LOG_INFO = 1;
export const LOG_WARNING = 2;
export const LOG_ERROR = 3;
export const LOG_FATAL = 4;
export const LOG_HOST_MISBEHAVING = 5;
export const LOG_PLUGIN_MISBEHAVING = 6;
export const EXT_LOG = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x6c,0x6f,0x67,0x0]); // clap.log
@unmanaged
export class clap_host_log {
	_log : usize; // (const clap_host_t *host,clap_log_severity severity,const char *msg) -> void
}

//---------- ext/note-name.h
export const EXT_NOTE_NAME = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x6e,0x6f,0x74,0x65,0x2d,0x6e,0x61,0x6d,0x65,0x0]); // clap.note-name
@unmanaged
export class clap_note_name {
	@array(256) _name : i8;
	_port : i16;
	_key : i16;
	_channel : i16;
}
@unmanaged
export class clap_plugin_note_name {
	_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get : usize; // (const clap_plugin_t *plugin,uint32_t index,clap_note_name_t *note_name) -> bool
}
@unmanaged
export class clap_host_note_name {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- ext/note-ports.h
export const NOTE_DIALECT_CLAP = 1 << 0;
export const NOTE_DIALECT_MIDI = 1 << 1;
export const NOTE_DIALECT_MIDI_MPE = 1 << 2;
export const NOTE_PORTS_RESCAN_ALL = 1 << 0;
export const NOTE_PORTS_RESCAN_NAMES = 1 << 1;
export const EXT_NOTE_PORTS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x6e,0x6f,0x74,0x65,0x2d,0x70,0x6f,0x72,0x74,0x73,0x0]); // clap.note-ports
@unmanaged
export class clap_note_port_info {
	_id : clap_id;
	_supported_dialects : u32;
	_preferred_dialect : u32;
	@array(256) _name : i8;
}
@unmanaged
export class clap_plugin_note_ports {
	_count : usize; // (const clap_plugin_t *plugin,bool is_input) -> uint32_t
	_get : usize; // (const clap_plugin_t *plugin,uint32_t index,bool is_input,clap_note_port_info_t *info) -> bool
}
@unmanaged
export class clap_host_note_ports {
	_supported_dialects : usize; // (const clap_host_t *host) -> uint32_t
	_rescan : usize; // (const clap_host_t *host,uint32_t flags) -> void
}

//---------- ext/params.h
export type clap_param_info_flags = u32;
export type clap_param_rescan_flags = u32;
export type clap_param_clear_flags = u32;
export const PARAM_IS_STEPPED = 1 << 0;
export const PARAM_IS_PERIODIC = 1 << 1;
export const PARAM_IS_HIDDEN = 1 << 2;
export const PARAM_IS_READONLY = 1 << 3;
export const PARAM_IS_BYPASS = 1 << 4;
export const PARAM_IS_AUTOMATABLE = 1 << 5;
export const PARAM_IS_AUTOMATABLE_PER_NOTE_ID = 1 << 6;
export const PARAM_IS_AUTOMATABLE_PER_KEY = 1 << 7;
export const PARAM_IS_AUTOMATABLE_PER_CHANNEL = 1 << 8;
export const PARAM_IS_AUTOMATABLE_PER_PORT = 1 << 9;
export const PARAM_IS_MODULATABLE = 1 << 10;
export const PARAM_IS_MODULATABLE_PER_NOTE_ID = 1 << 11;
export const PARAM_IS_MODULATABLE_PER_KEY = 1 << 12;
export const PARAM_IS_MODULATABLE_PER_CHANNEL = 1 << 13;
export const PARAM_IS_MODULATABLE_PER_PORT = 1 << 14;
export const PARAM_REQUIRES_PROCESS = 1 << 15;
export const PARAM_IS_ENUM = 1 << 16;
export const PARAM_RESCAN_VALUES = 1 << 0;
export const PARAM_RESCAN_TEXT = 1 << 1;
export const PARAM_RESCAN_INFO = 1 << 2;
export const PARAM_RESCAN_ALL = 1 << 3;
export const PARAM_CLEAR_ALL = 1 << 0;
export const PARAM_CLEAR_AUTOMATIONS = 1 << 1;
export const PARAM_CLEAR_MODULATIONS = 1 << 2;
export const EXT_PARAMS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x61,0x72,0x61,0x6d,0x73,0x0]); // clap.params
@unmanaged
export class clap_param_info {
	_id : clap_id;
	_flags : clap_param_info_flags;
	_cookie : usize; // void *
	@array(256) _name : i8;
	@array(1024) _module : i8;
	_min_value : f64;
	_max_value : f64;
	_default_value : f64;
}
@unmanaged
export class clap_plugin_params {
	_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get_info : usize; // (const clap_plugin_t *plugin,uint32_t param_index,clap_param_info_t *param_info) -> bool
	_get_value : usize; // (const clap_plugin_t *plugin,clap_id param_id,double *out_value) -> bool
	_value_to_text : usize; // (const clap_plugin_t *plugin,clap_id param_id,double value,char *out_buffer,uint32_t out_buffer_capacity) -> bool
	_text_to_value : usize; // (const clap_plugin_t *plugin,clap_id param_id,const char *param_value_text,double *out_value) -> bool
	_flush : usize; // (const clap_plugin_t *plugin,const clap_input_events_t *in,const clap_output_events_t *out) -> void
}
@unmanaged
export class clap_host_params {
	_rescan : usize; // (const clap_host_t *host,clap_param_rescan_flags flags) -> void
	_clear : usize; // (const clap_host_t *host,clap_id param_id,clap_param_clear_flags flags) -> void
	_request_flush : usize; // (const clap_host_t *host) -> void
}

//---------- color.h
@unmanaged
export class clap_color {
	_alpha : u8;
	_red : u8;
	_green : u8;
	_blue : u8;
}

//---------- ext/param-indication.h
export const PARAM_INDICATION_AUTOMATION_NONE = 0;
export const PARAM_INDICATION_AUTOMATION_PRESENT = 1;
export const PARAM_INDICATION_AUTOMATION_PLAYING = 2;
export const PARAM_INDICATION_AUTOMATION_RECORDING = 3;
export const PARAM_INDICATION_AUTOMATION_OVERRIDING = 4;
export const EXT_PARAM_INDICATION = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x61,0x72,0x61,0x6d,0x2d,0x69,0x6e,0x64,0x69,0x63,0x61,0x74,0x69,0x6f,0x6e,0x2f,0x34,0x0]); // clap.param-indication/4
export const EXT_PARAM_INDICATION_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x61,0x72,0x61,0x6d,0x2d,0x69,0x6e,0x64,0x69,0x63,0x61,0x74,0x69,0x6f,0x6e,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x34,0x0]); // clap.param-indication.draft/4
@unmanaged
export class clap_plugin_param_indication {
	_set_mapping : usize; // (const clap_plugin_t *plugin,clap_id param_id,bool has_mapping,const clap_color_t *color,const char *label,const char *description) -> void
	_set_automation : usize; // (const clap_plugin_t *plugin,clap_id param_id,uint32_t automation_state,const clap_color_t *color) -> void
}

//---------- ext/posix-fd-support.h
export type clap_posix_fd_flags_t = u32;
export const POSIX_FD_READ = 1 << 0;
export const POSIX_FD_WRITE = 1 << 1;
export const POSIX_FD_ERROR = 1 << 2;
export const EXT_POSIX_FD_SUPPORT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x6f,0x73,0x69,0x78,0x2d,0x66,0x64,0x2d,0x73,0x75,0x70,0x70,0x6f,0x72,0x74,0x0]); // clap.posix-fd-support
@unmanaged
export class clap_plugin_posix_fd_support {
	_on_fd : usize; // (const clap_plugin_t *plugin,int fd,clap_posix_fd_flags_t flags) -> void
}
@unmanaged
export class clap_host_posix_fd_support {
	_register_fd : usize; // (const clap_host_t *host,int fd,clap_posix_fd_flags_t flags) -> bool
	_modify_fd : usize; // (const clap_host_t *host,int fd,clap_posix_fd_flags_t flags) -> bool
	_unregister_fd : usize; // (const clap_host_t *host,int fd) -> bool
}

//---------- ext/preset-load.h
export const EXT_PRESET_LOAD = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x72,0x65,0x73,0x65,0x74,0x2d,0x6c,0x6f,0x61,0x64,0x2f,0x32,0x0]); // clap.preset-load/2
export const EXT_PRESET_LOAD_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x72,0x65,0x73,0x65,0x74,0x2d,0x6c,0x6f,0x61,0x64,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x32,0x0]); // clap.preset-load.draft/2
@unmanaged
export class clap_plugin_preset_load {
	_from_location : usize; // (const clap_plugin_t *plugin,uint32_t location_kind,const char *location,const char *load_key) -> bool
}
@unmanaged
export class clap_host_preset_load {
	_on_error : usize; // (const clap_host_t *host,uint32_t location_kind,const char *location,const char *load_key,int32_t os_error,const char *msg) -> void
	_loaded : usize; // (const clap_host_t *host,uint32_t location_kind,const char *location,const char *load_key) -> void
}

//---------- ext/remote-controls.h
export const EXT_REMOTE_CONTROLS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x72,0x65,0x6d,0x6f,0x74,0x65,0x2d,0x63,0x6f,0x6e,0x74,0x72,0x6f,0x6c,0x73,0x2f,0x32,0x0]); // clap.remote-controls/2
export const EXT_REMOTE_CONTROLS_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x72,0x65,0x6d,0x6f,0x74,0x65,0x2d,0x63,0x6f,0x6e,0x74,0x72,0x6f,0x6c,0x73,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x32,0x0]); // clap.remote-controls.draft/2
@unmanaged
export class clap_remote_controls_page {
	@array(256) _section_name : i8;
	_page_id : clap_id;
	@array(256) _page_name : i8;
	@array(8) _param_ids : clap_id;
	_is_for_preset : bool;
}
@unmanaged
export class clap_plugin_remote_controls {
	_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get : usize; // (const clap_plugin_t *plugin,uint32_t page_index,clap_remote_controls_page_t *page) -> bool
}
@unmanaged
export class clap_host_remote_controls {
	_changed : usize; // (const clap_host_t *host) -> void
	_suggest_page : usize; // (const clap_host_t *host,clap_id page_id) -> void
}

//---------- ext/render.h
export type clap_plugin_render_mode = i32;
export const RENDER_REALTIME = 0;
export const RENDER_OFFLINE = 1;
export const EXT_RENDER = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x72,0x65,0x6e,0x64,0x65,0x72,0x0]); // clap.render
@unmanaged
export class clap_plugin_render {
	_has_hard_realtime_requirement : usize; // (const clap_plugin_t *plugin) -> bool
	_set : usize; // (const clap_plugin_t *plugin,clap_plugin_render_mode mode) -> bool
}

//---------- stream.h
@unmanaged
export class clap_istream {
	_ctx : usize; // void *
	_read : usize; // (const struct clap_istream *stream,void *buffer,uint64_t size) -> int64_t
}
@unmanaged
export class clap_ostream {
	_ctx : usize; // void *
	_write : usize; // (const struct clap_ostream *stream,const void *buffer,uint64_t size) -> int64_t
}

//---------- ext/state-context.h
export const STATE_CONTEXT_FOR_PRESET = 1;
export const STATE_CONTEXT_FOR_DUPLICATE = 2;
export const STATE_CONTEXT_FOR_PROJECT = 3;
export const EXT_STATE_CONTEXT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x73,0x74,0x61,0x74,0x65,0x2d,0x63,0x6f,0x6e,0x74,0x65,0x78,0x74,0x2f,0x32,0x0]); // clap.state-context/2
@unmanaged
export class clap_plugin_state_context {
	_save : usize; // (const clap_plugin_t *plugin,const clap_ostream_t *stream,uint32_t context_type) -> bool
	_load : usize; // (const clap_plugin_t *plugin,const clap_istream_t *stream,uint32_t context_type) -> bool
}

//---------- ext/state.h
export const EXT_STATE = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x73,0x74,0x61,0x74,0x65,0x0]); // clap.state
@unmanaged
export class clap_plugin_state {
	_save : usize; // (const clap_plugin_t *plugin,const clap_ostream_t *stream) -> bool
	_load : usize; // (const clap_plugin_t *plugin,const clap_istream_t *stream) -> bool
}
@unmanaged
export class clap_host_state {
	_mark_dirty : usize; // (const clap_host_t *host) -> void
}

//---------- ext/surround.h
export const SURROUND_FL = 0;
export const SURROUND_FR = 1;
export const SURROUND_FC = 2;
export const SURROUND_LFE = 3;
export const SURROUND_BL = 4;
export const SURROUND_BR = 5;
export const SURROUND_FLC = 6;
export const SURROUND_FRC = 7;
export const SURROUND_BC = 8;
export const SURROUND_SL = 9;
export const SURROUND_SR = 10;
export const SURROUND_TC = 11;
export const SURROUND_TFL = 12;
export const SURROUND_TFC = 13;
export const SURROUND_TFR = 14;
export const SURROUND_TBL = 15;
export const SURROUND_TBC = 16;
export const SURROUND_TBR = 17;
export const SURROUND_TSL = 18;
export const SURROUND_TSR = 19;
export const EXT_SURROUND = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x73,0x75,0x72,0x72,0x6f,0x75,0x6e,0x64,0x2f,0x34,0x0]); // clap.surround/4
export const EXT_SURROUND_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x73,0x75,0x72,0x72,0x6f,0x75,0x6e,0x64,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x34,0x0]); // clap.surround.draft/4
export const PORT_SURROUND = memory.data<u8>([0x73,0x75,0x72,0x72,0x6f,0x75,0x6e,0x64,0x0]); // surround
@unmanaged
export class clap_plugin_surround {
	_is_channel_mask_supported : usize; // (const clap_plugin_t *plugin,uint64_t channel_mask) -> bool
	_get_channel_map : usize; // (const clap_plugin_t *plugin,bool is_input,uint32_t port_index,uint8_t *channel_map,uint32_t channel_map_capacity) -> uint32_t
}
@unmanaged
export class clap_host_surround {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- ext/tail.h
export const EXT_TAIL = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x61,0x69,0x6c,0x0]); // clap.tail
@unmanaged
export class clap_plugin_tail {
	_get : usize; // (const clap_plugin_t *plugin) -> uint32_t
}
@unmanaged
export class clap_host_tail {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- ext/thread-check.h
export const EXT_THREAD_CHECK = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x68,0x72,0x65,0x61,0x64,0x2d,0x63,0x68,0x65,0x63,0x6b,0x0]); // clap.thread-check
@unmanaged
export class clap_host_thread_check {
	_is_main_thread : usize; // (const clap_host_t *host) -> bool
	_is_audio_thread : usize; // (const clap_host_t *host) -> bool
}

//---------- ext/thread-pool.h
export const EXT_THREAD_POOL = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x68,0x72,0x65,0x61,0x64,0x2d,0x70,0x6f,0x6f,0x6c,0x0]); // clap.thread-pool
@unmanaged
export class clap_plugin_thread_pool {
	_exec : usize; // (const clap_plugin_t *plugin,uint32_t task_index) -> void
}
@unmanaged
export class clap_host_thread_pool {
	_request_exec : usize; // (const clap_host_t *host,uint32_t num_tasks) -> bool
}

//---------- ext/timer-support.h
export const EXT_TIMER_SUPPORT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x69,0x6d,0x65,0x72,0x2d,0x73,0x75,0x70,0x70,0x6f,0x72,0x74,0x0]); // clap.timer-support
@unmanaged
export class clap_plugin_timer_support {
	_on_timer : usize; // (const clap_plugin_t *plugin,clap_id timer_id) -> void
}
@unmanaged
export class clap_host_timer_support {
	_register_timer : usize; // (const clap_host_t *host,uint32_t period_ms,clap_id *timer_id) -> bool
	_unregister_timer : usize; // (const clap_host_t *host,clap_id timer_id) -> bool
}

//---------- ext/track-info.h
export const EXT_TRACK_INFO = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x72,0x61,0x63,0x6b,0x2d,0x69,0x6e,0x66,0x6f,0x2f,0x31,0x0]); // clap.track-info/1
export const EXT_TRACK_INFO_COMPAT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x72,0x61,0x63,0x6b,0x2d,0x69,0x6e,0x66,0x6f,0x2e,0x64,0x72,0x61,0x66,0x74,0x2f,0x31,0x0]); // clap.track-info.draft/1
@unmanaged
export class clap_track_info {
	_flags : u64;
	@array(256) _name : i8;
	// color: clap_color
	_color_alpha : u8;
	_color_red : u8;
	_color_green : u8;
	_color_blue : u8;
	@inline get _color() : clap_color {
		return changetype<clap_color>(changetype<usize>(this) + offsetof<clap_track_info>("_color_alpha"))
	}
	_audio_channel_count : i32;
	_audio_port_type : usize; // const char *
}
@unmanaged
export class clap_plugin_track_info {
	_changed : usize; // (const clap_plugin_t *plugin) -> void
}
@unmanaged
export class clap_host_track_info {
	_get : usize; // (const clap_host_t *host,clap_track_info_t *info) -> bool
}

//---------- ext/voice-info.h
export const VOICE_INFO_SUPPORTS_OVERLAPPING_NOTES = 1 << 0;
export const EXT_VOICE_INFO = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x76,0x6f,0x69,0x63,0x65,0x2d,0x69,0x6e,0x66,0x6f,0x0]); // clap.voice-info
@unmanaged
export class clap_voice_info {
	_voice_count : u32;
	_voice_capacity : u32;
	_flags : u64;
}
@unmanaged
export class clap_plugin_voice_info {
	_get : usize; // (const clap_plugin_t *plugin,clap_voice_info_t *info) -> bool
}
@unmanaged
export class clap_host_voice_info {
	_changed : usize; // (const clap_host_t *host) -> void
}

//---------- clap.h

//---------- factory/draft/plugin-invalidation.h
@unmanaged
export class clap_plugin_invalidation_source {
	_directory : usize; // const char *
	_filename_glob : usize; // const char *
	_recursive_scan : bool;
}
@unmanaged
export class clap_plugin_invalidation_factory {
	_count : usize; // (const struct clap_plugin_invalidation_factory *factory) -> uint32_t
	_get : usize; // (const struct clap_plugin_invalidation_factory *factory,uint32_t index) -> const clap_plugin_invalidation_source_t *
	_refresh : usize; // (const struct clap_plugin_invalidation_factory *factory) -> bool
}

//---------- factory/draft/plugin-state-converter.h
export const PLUGIN_STATE_CONVERTER_FACTORY_ID = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x6c,0x75,0x67,0x69,0x6e,0x2d,0x73,0x74,0x61,0x74,0x65,0x2d,0x63,0x6f,0x6e,0x76,0x65,0x72,0x74,0x65,0x72,0x2d,0x66,0x61,0x63,0x74,0x6f,0x72,0x79,0x2f,0x31,0x0]); // clap.plugin-state-converter-factory/1
@unmanaged
export class clap_plugin_state_converter_descriptor {
	// clap_version: clap_version
	_clap_version_major : u32;
	_clap_version_minor : u32;
	_clap_version_revision : u32;
	@inline get _clap_version() : clap_version {
		return changetype<clap_version>(changetype<usize>(this) + offsetof<clap_plugin_state_converter_descriptor>("_clap_version_major"))
	}
	// src_plugin_id: clap_universal_plugin_id
	_src_plugin_id_abi : usize; //  // const char *
	_src_plugin_id_id : usize; //  // const char *
	@inline get _src_plugin_id() : clap_universal_plugin_id {
		return changetype<clap_universal_plugin_id>(changetype<usize>(this) + offsetof<clap_plugin_state_converter_descriptor>("_src_plugin_id_abi"))
	}
	// dst_plugin_id: clap_universal_plugin_id
	_dst_plugin_id_abi : usize; //  // const char *
	_dst_plugin_id_id : usize; //  // const char *
	@inline get _dst_plugin_id() : clap_universal_plugin_id {
		return changetype<clap_universal_plugin_id>(changetype<usize>(this) + offsetof<clap_plugin_state_converter_descriptor>("_dst_plugin_id_abi"))
	}
	_id : usize; // const char *
	_name : usize; // const char *
	_vendor : usize; // const char *
	_version : usize; // const char *
	_description : usize; // const char *
}
@unmanaged
export class clap_plugin_state_converter {
	_desc : usize; // const clap_plugin_state_converter_descriptor_t *
	_converter_data : usize; // void *
	_destroy : usize; // (struct clap_plugin_state_converter *converter) -> void
	_convert_state : usize; // (struct clap_plugin_state_converter *converter,const clap_istream_t *src,const clap_ostream_t *dst,char *error_buffer,size_t error_buffer_size) -> bool
	_convert_normalized_value : usize; // (struct clap_plugin_state_converter *converter,clap_id src_param_id,double src_normalized_value,clap_id *dst_param_id,double *dst_normalized_value) -> bool
	_convert_plain_value : usize; // (struct clap_plugin_state_converter *converter,clap_id src_param_id,double src_plain_value,clap_id *dst_param_id,double *dst_plain_value) -> bool
}
@unmanaged
export class clap_plugin_state_converter_factory {
	_count : usize; // (const struct clap_plugin_state_converter_factory *factory) -> uint32_t
	_get_descriptor : usize; // (const struct clap_plugin_state_converter_factory *factory,uint32_t index) -> const clap_plugin_state_converter_descriptor_t *
	_create : usize; // (const struct clap_plugin_state_converter_factory *factory,const char *converter_id) -> clap_plugin_state_converter_t *
}

//---------- ext/draft/extensible-audio-ports.h
export const EXT_EXTENSIBLE_AUDIO_PORTS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x65,0x78,0x74,0x65,0x6e,0x73,0x69,0x62,0x6c,0x65,0x2d,0x61,0x75,0x64,0x69,0x6f,0x2d,0x70,0x6f,0x72,0x74,0x73,0x2f,0x31,0x0]); // clap.extensible-audio-ports/1
@unmanaged
export class clap_plugin_extensible_audio_ports {
	_add_port : usize; // (const clap_plugin_t *plugin,bool is_input,uint32_t channel_count,const char *port_type,const void *port_details) -> bool
	_remove_port : usize; // (const clap_plugin_t *plugin,bool is_input,uint32_t index) -> bool
}

//---------- ext/draft/gain-adjustment-metering.h
export const EXT_GAIN_ADJUSTMENT_METERING = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x67,0x61,0x69,0x6e,0x2d,0x61,0x64,0x6a,0x75,0x73,0x74,0x6d,0x65,0x6e,0x74,0x2d,0x6d,0x65,0x74,0x65,0x72,0x69,0x6e,0x67,0x2f,0x30,0x0]); // clap.gain-adjustment-metering/0
@unmanaged
export class clap_plugin_gain_adjustment_metering {
	_get : usize; // (const clap_plugin_t *plugin) -> double
}

//---------- ext/draft/mini-curve-display.h
export const MINI_CURVE_DISPLAY_CURVE_KIND_UNSPECIFIED = 0;
export const MINI_CURVE_DISPLAY_CURVE_KIND_GAIN_RESPONSE = 1;
export const MINI_CURVE_DISPLAY_CURVE_KIND_PHASE_RESPONSE = 2;
export const MINI_CURVE_DISPLAY_CURVE_KIND_TRANSFER_CURVE = 3;
export const MINI_CURVE_DISPLAY_CURVE_KIND_GAIN_REDUCTION = 4;
export const MINI_CURVE_DISPLAY_CURVE_KIND_TIME_SERIES = 5;
export const MINI_CURVE_DISPLAY_CURVE_CHANGED = 1 << 0;
export const MINI_CURVE_DISPLAY_AXIS_NAME_CHANGED = 1 << 1;
export const EXT_MINI_CURVE_DISPLAY = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x6d,0x69,0x6e,0x69,0x2d,0x63,0x75,0x72,0x76,0x65,0x2d,0x64,0x69,0x73,0x70,0x6c,0x61,0x79,0x2f,0x33,0x0]); // clap.mini-curve-display/3
@unmanaged
export class clap_mini_curve_display_curve_hints {
	_x_min : f64;
	_x_max : f64;
	_y_min : f64;
	_y_max : f64;
}
@unmanaged
export class clap_mini_curve_display_curve_data {
	_curve_kind : i32;
	_values : usize; // uint16_t *
	_values_count : u32;
}
@unmanaged
export class clap_plugin_mini_curve_display {
	_get_curve_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_render : usize; // (const clap_plugin_t *plugin,clap_mini_curve_display_curve_data_t *curves,uint32_t curves_size) -> uint32_t
	_set_observed : usize; // (const clap_plugin_t *plugin,bool is_observed) -> void
	_get_axis_name : usize; // (const clap_plugin_t *plugin,uint32_t curve_index,char *x_name,char *y_name,uint32_t name_capacity) -> bool
}
@unmanaged
export class clap_host_mini_curve_display {
	_get_hints : usize; // (const clap_host_t *host,uint32_t kind,clap_mini_curve_display_curve_hints_t *hints) -> bool
	_set_dynamic : usize; // (const clap_host_t *host,bool is_dynamic) -> void
	_changed : usize; // (const clap_host_t *host,uint32_t flags) -> void
}

//---------- ext/draft/project-location.h
export const PROJECT_LOCATION_PROJECT = 1;
export const PROJECT_LOCATION_TRACK_GROUP = 2;
export const PROJECT_LOCATION_TRACK = 3;
export const PROJECT_LOCATION_DEVICE = 4;
export const PROJECT_LOCATION_NESTED_DEVICE_CHAIN = 5;
export const PROJECT_LOCATION_INSTUMENT_TRACK = 1;
export const PROJECT_LOCATION_AUDIO_TRACK = 2;
export const PROJECT_LOCATION_HYBRID_TRACK = 3;
export const PROJECT_LOCATION_RETURN_TRACK = 4;
export const PROJECT_LOCATION_MASTER_TRACK = 5;
export const PROJECT_LOCATION_HAS_INDEX = 1 << 0;
export const PROJECT_LOCATION_HAS_COLOR = 1 << 1;
export const EXT_PROJECT_LOCATION = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x70,0x72,0x6f,0x6a,0x65,0x63,0x74,0x2d,0x6c,0x6f,0x63,0x61,0x74,0x69,0x6f,0x6e,0x2f,0x32,0x0]); // clap.project-location/2
@unmanaged
export class clap_project_location_element {
	_flags : u64;
	_kind : u32;
	_track_kind : u32;
	_index : u32;
	@array(1024) _id : i8;
	@array(256) _name : i8;
	// color: clap_color
	_color_alpha : u8;
	_color_red : u8;
	_color_green : u8;
	_color_blue : u8;
	@inline get _color() : clap_color {
		return changetype<clap_color>(changetype<usize>(this) + offsetof<clap_project_location_element>("_color_alpha"))
	}
}
@unmanaged
export class clap_plugin_project_location {
	_set : usize; // (const clap_plugin_t *plugin,const clap_project_location_element_t *path,uint32_t num_elements) -> void
}

//---------- ext/draft/resource-directory.h
export const EXT_RESOURCE_DIRECTORY = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x72,0x65,0x73,0x6f,0x75,0x72,0x63,0x65,0x2d,0x64,0x69,0x72,0x65,0x63,0x74,0x6f,0x72,0x79,0x2f,0x31,0x0]); // clap.resource-directory/1
@unmanaged
export class clap_plugin_resource_directory {
	_set_directory : usize; // (const clap_plugin_t *plugin,const char *path,bool is_shared) -> void
	_collect : usize; // (const clap_plugin_t *plugin,bool all) -> void
	_get_files_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get_file_path : usize; // (const clap_plugin_t *plugin,uint32_t index,char *path,uint32_t path_size) -> int32_t
}
@unmanaged
export class clap_host_resource_directory {
	_request_directory : usize; // (const clap_host_t *host,bool is_shared) -> bool
	_release_directory : usize; // (const clap_host_t *host,bool is_shared) -> void
}

//---------- ext/draft/scratch-memory.h
export const EXT_SCRATCH_MEMORY = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x73,0x63,0x72,0x61,0x74,0x63,0x68,0x2d,0x6d,0x65,0x6d,0x6f,0x72,0x79,0x2f,0x31,0x0]); // clap.scratch-memory/1
@unmanaged
export class clap_host_scratch_memory {
	_reserve : usize; // (const clap_host_t *host,uint32_t scratch_size_bytes,uint32_t max_concurrency_hint) -> bool
	_access : usize; // (const clap_host_t *host) -> void *
}

//---------- ext/draft/transport-control.h
export const EXT_TRANSPORT_CONTROL = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x72,0x61,0x6e,0x73,0x70,0x6f,0x72,0x74,0x2d,0x63,0x6f,0x6e,0x74,0x72,0x6f,0x6c,0x2f,0x31,0x0]); // clap.transport-control/1
@unmanaged
export class clap_host_transport_control {
	_request_start : usize; // (const clap_host_t *host) -> void
	_request_stop : usize; // (const clap_host_t *host) -> void
	_request_continue : usize; // (const clap_host_t *host) -> void
	_request_pause : usize; // (const clap_host_t *host) -> void
	_request_toggle_play : usize; // (const clap_host_t *host) -> void
	_request_jump : usize; // (const clap_host_t *host,clap_beattime position) -> void
	_request_loop_region : usize; // (const clap_host_t *host,clap_beattime start,clap_beattime duration) -> void
	_request_toggle_loop : usize; // (const clap_host_t *host) -> void
	_request_enable_loop : usize; // (const clap_host_t *host,bool is_enabled) -> void
	_request_record : usize; // (const clap_host_t *host,bool is_recording) -> void
	_request_toggle_record : usize; // (const clap_host_t *host) -> void
}

//---------- ext/draft/triggers.h
export type clap_trigger_info_flags = u32;
export type clap_trigger_rescan_flags = u32;
export type clap_trigger_clear_flags = u32;
export const TRIGGER_IS_AUTOMATABLE_PER_NOTE_ID = 1 << 0;
export const TRIGGER_IS_AUTOMATABLE_PER_KEY = 1 << 1;
export const TRIGGER_IS_AUTOMATABLE_PER_CHANNEL = 1 << 2;
export const TRIGGER_IS_AUTOMATABLE_PER_PORT = 1 << 3;
export const EVENT_TRIGGER = 0;
export const TRIGGER_RESCAN_INFO = 1 << 0;
export const TRIGGER_RESCAN_ALL = 1 << 1;
export const TRIGGER_CLEAR_ALL = 1 << 0;
export const TRIGGER_CLEAR_AUTOMATIONS = 1 << 1;
export const EXT_TRIGGERS = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x72,0x69,0x67,0x67,0x65,0x72,0x73,0x2f,0x31,0x0]); // clap.triggers/1
@unmanaged
export class clap_event_trigger {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_trigger>("_header_size"))
	}
	_trigger_id : clap_id;
	_cookie : usize; // void *
	_note_id : i32;
	_port_index : i16;
	_channel : i16;
	_key : i16;
}
@unmanaged
export class clap_trigger_info {
	_id : clap_id;
	_flags : clap_trigger_info_flags;
	_cookie : usize; // void *
	@array(256) _name : i8;
	@array(1024) _module : i8;
}
@unmanaged
export class clap_plugin_triggers {
	_count : usize; // (const clap_plugin_t *plugin) -> uint32_t
	_get_info : usize; // (const clap_plugin_t *plugin,uint32_t index,clap_trigger_info_t *trigger_info) -> bool
}
@unmanaged
export class clap_host_triggers {
	_rescan : usize; // (const clap_host_t *host,clap_trigger_rescan_flags flags) -> void
	_clear : usize; // (const clap_host_t *host,clap_id trigger_id,clap_trigger_clear_flags flags) -> void
}

//---------- ext/draft/tuning.h
export const EXT_TUNING = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x74,0x75,0x6e,0x69,0x6e,0x67,0x2f,0x32,0x0]); // clap.tuning/2
@unmanaged
export class clap_event_tuning {
	// header: clap_event_header
	_header_size : u32;
	_header_time : u32;
	_header_space_id : u16;
	_header_type : u16;
	_header_flags : u32;
	@inline get _header() : clap_event_header {
		return changetype<clap_event_header>(changetype<usize>(this) + offsetof<clap_event_tuning>("_header_size"))
	}
	_port_index : i16;
	_channel : i16;
	_tunning_id : clap_id;
}
@unmanaged
export class clap_tuning_info {
	_tuning_id : clap_id;
	@array(256) _name : i8;
	_is_dynamic : bool;
}
@unmanaged
export class clap_plugin_tuning {
	_changed : usize; // (const clap_plugin_t *plugin) -> void
}
@unmanaged
export class clap_host_tuning {
	_get_relative : usize; // (const clap_host_t *host,clap_id tuning_id,int32_t channel,int32_t key,uint32_t sample_offset) -> double
	_should_play : usize; // (const clap_host_t *host,clap_id tuning_id,int32_t channel,int32_t key) -> bool
	_get_tuning_count : usize; // (const clap_host_t *host) -> uint32_t
	_get_info : usize; // (const clap_host_t *host,uint32_t tuning_index,clap_tuning_info_t *info) -> bool
}

//---------- ext/draft/undo.h
export const EXT_UNDO = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x75,0x6e,0x64,0x6f,0x2f,0x34,0x0]); // clap.undo/4
export const EXT_UNDO_CONTEXT = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x75,0x6e,0x64,0x6f,0x5f,0x63,0x6f,0x6e,0x74,0x65,0x78,0x74,0x2f,0x34,0x0]); // clap.undo_context/4
export const EXT_UNDO_DELTA = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x75,0x6e,0x64,0x6f,0x5f,0x64,0x65,0x6c,0x74,0x61,0x2f,0x34,0x0]); // clap.undo_delta/4
@unmanaged
export class clap_undo_delta_properties {
	_has_delta : bool;
	_are_deltas_persistent : bool;
	_format_version : clap_id;
}
@unmanaged
export class clap_plugin_undo_delta {
	_get_delta_properties : usize; // (const clap_plugin_t *plugin,clap_undo_delta_properties_t *properties) -> void
	_can_use_delta_format_version : usize; // (const clap_plugin_t *plugin,clap_id format_version) -> bool
	_undo : usize; // (const clap_plugin_t *plugin,clap_id format_version,const void *delta,size_t delta_size) -> bool
	_redo : usize; // (const clap_plugin_t *plugin,clap_id format_version,const void *delta,size_t delta_size) -> bool
}
@unmanaged
export class clap_plugin_undo_context {
	_set_can_undo : usize; // (const clap_plugin_t *plugin,bool can_undo) -> void
	_set_can_redo : usize; // (const clap_plugin_t *plugin,bool can_redo) -> void
	_set_undo_name : usize; // (const clap_plugin_t *plugin,const char *name) -> void
	_set_redo_name : usize; // (const clap_plugin_t *plugin,const char *name) -> void
}
@unmanaged
export class clap_host_undo {
	_begin_change : usize; // (const clap_host_t *host) -> void
	_cancel_change : usize; // (const clap_host_t *host) -> void
	_change_made : usize; // (const clap_host_t *host,const char *name,const void *delta,size_t delta_size,bool delta_can_undo) -> void
	_request_undo : usize; // (const clap_host_t *host) -> void
	_request_redo : usize; // (const clap_host_t *host) -> void
	_set_wants_context_updates : usize; // (const clap_host_t *host,bool is_subscribed) -> void
}

//---------- ext/draft/webview.h
export const EXT_WEBVIEW = memory.data<u8>([0x63,0x6c,0x61,0x70,0x2e,0x77,0x65,0x62,0x76,0x69,0x65,0x77,0x2f,0x33,0x0]); // clap.webview/3
@unmanaged
export class clap_plugin_webview {
	_get_uri : usize; // (const clap_plugin_t *plugin,char *uri,uint32_t uri_capacity) -> int32_t
	_get_resource : usize; // (const clap_plugin_t *plugin,const char *path,char *mime,uint32_t mime_capacity,const clap_ostream_t *data_stream) -> bool
	_receive : usize; // (const clap_plugin_t *plugin,const void *buffer,uint32_t size) -> bool
}
@unmanaged
export class clap_host_webview {
	_send : usize; // (const clap_host_t *host,const void *buffer,uint32_t size) -> bool
}

//---------- all.h
